databases:
  - name: dpg-cne4g75jm4es739np0n0-a
    databaseName: apigen_dp3b
    user: apigen_dp3b_user

services:
  - type: web
    name: apiweb-gen
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: potencia-tech
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4